name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  ROBO_URL:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - name: Install z
      run: sudo curl -sSL gobinaries.com/zakuro9715/z | sh
    - name: Build
      run: z build
    - name: Lint
      run: z lint
    - name: Test
      run: z test
