name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  ROBO_URL:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get robo
      run: bash scripts/get_robo.bash && sudo mv robo /usr/local/bin/
    - name: Build
      run: robo build --verbose
    - name: Lint
      run: robo lint
    - name: Test
      run: robo test  --verbose
